### ISSUE TITLE
Proposal: VisibleForAccessors

### ISSUE THREAD

**Issue by ZacSweers** [google/error-prone#765] opened 2017-10-08 08:11 UTC
On android we have method limits, and one means of mitigating them is to avoid synthetic accessor methods. A downside of this would be that sometimes you're left making certain things package-local when you'd normally make them private. What would you think of an annotation like `@VisibleForAccessors(otherwise = PRIVATE)`? Similar to `@VisibleForTesting`, but to enforce these are treated the same way as `otherwise` (whose value could default to `PRIVATE`) during compilation,

**Comment by hzsweers** [comment] 2017-10-08 08:11
An example: https://github.com/uber/AutoDispose/pull/103

**Comment by NightlyNexus** [comment] 2017-10-08 09:45
There is an Android Lint rule for `@RestrictTo`, as you know, but this proposal may be handy for non-Android libraries.

My personal experience is that Java's `private` keyword is useless noise in libraries and all feature-package organized code.
`@VisibleForAccessors(otherwise = PRIVATE)` would also be a lot of noise for little clarity or other benefit, in my opinion.

However, an annotation like this would be handy to apply to packages in Java libraries that organize some implementation details in separate packages like `internal`, so they could restrict consumers from using code not intended to be part of the API.

**Comment by JakeWharton** [comment] 2018-02-18 00:01
Dupe of #537

**Comment by JakeWharton** [comment] 2018-02-18 00:01
Or related to, at least

**Comment by bangarharshit** [comment] 2018-02-18 04:50
Error-Prone already has a check for RestrictTo [RestrictToEnforcer](https://github.com/google/error-prone/blob/ce85d0dbffdda303731cfebc44d49b7dd09aa1d1/core/src/main/java/com/google/errorprone/bugpatterns/android/RestrictToEnforcer.java). 

The only problem is that it needs android support annotations and just work to make sure that the API is internal to support the library.

It can be easily modified to suit this use case. I can send a PR if the error-prone team is ok about the check.

This issue can then be closed for 537.

**Closed** 2021-06-20 08:26 UTC
Labels: Type-NewCheck
