### ISSUE TITLE
Error in static analysis

### ISSUE THREAD

**Issue by jisharma-bb** [google/error-prone#2477] opened 2021-08-04 10:14 UTC
error-prone version: 2.3.3
     BugPattern: TypeParameterUnusedInFormals
     Stack Trace:
     java.lang.NoSuchFieldError: bound

**Comment by Stephan202** [comment] 2021-08-04 10:26
@jisharma-bb this issue looks like a duplicate of #1352 and several tickets. The issue can be resolved by upgrading Error Prone :)

**Closed** 2021-08-04 15:14 UTC
