### ISSUE TITLE
java.lang.ClassCastException: com.sun.tools.javac.tree.JCTree$JCIf cannot be cast to com.sun.source.tree.BlockTree

### ISSUE THREAD

**Issue by krisch187** [google/error-prone#732] opened 2017-08-29 13:11 UTC
OpenJDK Runtime Environment
1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11

```
00:08:37.808 [ERROR] [system.err] .../IndexList.java:164: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
00:08:37.809 [ERROR] [system.err] 			for (int i = 0; i < size; i++)
00:08:37.809 [ERROR] [system.err] 			^
00:08:37.809 [ERROR] [system.err]      Please report this at https://github.com/google/error-prone/issues/new and include the following:
00:08:37.809 [ERROR] [system.err]   
00:08:37.809 [ERROR] [system.err]      error-prone version: 2.1.0
00:08:37.809 [ERROR] [system.err]      Stack Trace:
00:08:37.809 [ERROR] [system.err]      java.lang.ClassCastException: com.sun.tools.javac.tree.JCTree$JCIf cannot be cast to com.sun.source.tree.BlockTree
00:08:37.810 [ERROR] [system.err]   	at com.google.errorprone.bugpatterns.IncrementInForLoopAndHeader.matchForLoop(IncrementInForLoopAndHeader.java:56)
00:08:37.810 [ERROR] [system.err]   	at com.google.errorprone.scanner.ErrorProneScanner.visitForLoop(ErrorProneScanner.java:722)
00:08:37.810 [ERROR] [system.err]   	at com.google.errorprone.scanner.ErrorProneScanner.visitForLoop(ErrorProneScanner.java:146)
00:08:37.810 [ERROR] [system.err]   	at com.sun.tools.javac.tree.JCTree$JCForLoop.accept(JCTree.java:1132)
00:08:37.810 [ERROR] [system.err]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
00:08:37.810 [ERROR] [system.err]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
00:08:37.810 [ERROR] [system.err]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
00:08:37.811 [ERROR] [system.err]   	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
00:08:37.811 [ERROR] [system.err]   	at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
00:08:37.811 [ERROR] [system.err]   	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:530)
00:08:37.811 [ERROR] [system.err]   	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:146)
00:08:37.811 [ERROR] [system.err]   	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
00:08:37.812 [ERROR] [system.err]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
00:08:37.812 [ERROR] [system.err]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
00:08:37.812 [ERROR] [system.err]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
00:08:37.812 [ERROR] [system.err]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
00:08:37.812 [ERROR] [system.err]   	at com.sun.source.util.TreeScanner.visitIf(TreeScanner.java:419)
00:08:37.812 [ERROR] [system.err]   	at com.google.errorprone.scanner.ErrorProneScanner.visitIf(ErrorProneScanner.java:758)
00:08:37.812 [ERROR] [system.err]   	at com.google.errorprone.scanner.ErrorProneScanner.visitIf(ErrorProneScanner.java:146)
00:08:37.812 [ERROR] [system.err]   	at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1427)
00:08:37.812 [ERROR] [system.err]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
00:08:37.812 [ERROR] [system.err]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
00:08:37.812 [ERROR] [system.err]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
00:08:37.812 [ERROR] [system.err]   	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
00:08:37.813 [ERROR] [system.err]   	at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
00:08:37.813 [ERROR] [system.err]   	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:530)
00:08:37.813 [ERROR] [system.err]   	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:146)
00:08:37.813 [ERROR] [system.err]   	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
00:08:37.813 [ERROR] [system.err]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
00:08:37.813 [ERROR] [system.err]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
00:08:37.813 [ERROR] [system.err]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
00:08:37.813 [ERROR] [system.err]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
00:08:37.813 [ERROR] [system.err]   	at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:206)
00:08:37.813 [ERROR] [system.err]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:898)
00:08:37.813 [ERROR] [system.err]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:146)
00:08:37.813 [ERROR] [system.err]   	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:898)
00:08:37.814 [ERROR] [system.err]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
00:08:37.814 [ERROR] [system.err]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
00:08:37.814 [ERROR] [system.err]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
00:08:37.814 [ERROR] [system.err]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
00:08:37.814 [ERROR] [system.err]   	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
00:08:37.814 [ERROR] [system.err]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
00:08:37.814 [ERROR] [system.err]   	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
00:08:37.814 [ERROR] [system.err]   	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:590)
00:08:37.814 [ERROR] [system.err]   	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:146)
00:08:37.814 [ERROR] [system.err]   	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
00:08:37.814 [ERROR] [system.err]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
00:08:37.814 [ERROR] [system.err]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
00:08:37.814 [ERROR] [system.err]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
00:08:37.815 [ERROR] [system.err]   	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
00:08:37.815 [ERROR] [system.err]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
00:08:37.815 [ERROR] [system.err]   	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
00:08:37.815 [ERROR] [system.err]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:605)
00:08:37.815 [ERROR] [system.err]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:146)
00:08:37.815 [ERROR] [system.err]   	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
00:08:37.815 [ERROR] [system.err]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
00:08:37.815 [ERROR] [system.err]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:64)
00:08:37.815 [ERROR] [system.err]   	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:41)
00:08:37.815 [ERROR] [system.err]   	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:145)
00:08:37.815 [ERROR] [system.err]   	at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
00:08:37.815 [ERROR] [system.err]   	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1425)
00:08:37.815 [ERROR] [system.err]   	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1374)
00:08:37.816 [ERROR] [system.err]   	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:973)
00:08:37.816 [ERROR] [system.err]   	at com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
00:08:37.816 [ERROR] [system.err]   	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
00:08:37.816 [ERROR] [system.err]   	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
00:08:37.816 [ERROR] [system.err]   	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
00:08:37.817 [ERROR] [system.err]   	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:137)
00:08:37.817 [ERROR] [system.err]   	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:108)
00:08:37.817 [ERROR] [system.err]   	at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:118)
00:08:37.817 [ERROR] [system.err]   	at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:65)
00:08:37.817 [ERROR] [system.err]   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:08:37.817 [ERROR] [system.err]   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:08:37.817 [ERROR] [system.err]   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:08:37.817 [ERROR] [system.err]   	at java.lang.reflect.Method.invoke(Method.java:498)
00:08:37.817 [ERROR] [system.err]   	at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:63)
00:08:37.817 [ERROR] [system.err]   	at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:24)
00:08:37.818 [ERROR] [system.err]   	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:99)
00:08:37.818 [ERROR] [system.err]   	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:52)
00:08:37.818 [ERROR] [system.err]   	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:37)
00:08:37.818 [ERROR] [system.err]   	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
00:08:37.818 [ERROR] [system.err]   	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
00:08:37.818 [ERROR] [system.err]   	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:198)
00:08:37.818 [ERROR] [system.err]   	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:183)
00:08:37.818 [ERROR] [system.err]   	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:120)
00:08:37.818 [ERROR] [system.err]   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:08:37.818 [ERROR] [system.err]   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:08:37.818 [ERROR] [system.err]   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:08:37.818 [ERROR] [system.err]   	at java.lang.reflect.Method.invoke(Method.java:498)
00:08:37.818 [ERROR] [system.err]   	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
00:08:37.818 [ERROR] [system.err]   	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:173)
00:08:37.819 [ERROR] [system.err]   	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
00:08:37.819 [ERROR] [system.err]   	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
00:08:37.819 [ERROR] [system.err]   	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
00:08:37.819 [ERROR] [system.err]   	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
00:08:37.819 [ERROR] [system.err]   	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
00:08:37.819 [ERROR] [system.err]   	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
00:08:37.819 [ERROR] [system.err]   	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
00:08:37.819 [ERROR] [system.err]   	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
00:08:37.820 [ERROR] [system.err]   	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
00:08:37.820 [ERROR] [system.err]   	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
00:08:37.820 [ERROR] [system.err]   	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
00:08:37.820 [ERROR] [system.err]   	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
00:08:37.820 [ERROR] [system.err]   	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
00:08:37.820 [ERROR] [system.err]   	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
00:08:37.820 [ERROR] [system.err]   	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
00:08:37.820 [ERROR] [system.err]   	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
00:08:37.820 [ERROR] [system.err]   	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
00:08:37.820 [ERROR] [system.err]   	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
00:08:37.820 [ERROR] [system.err]   	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
00:08:37.821 [ERROR] [system.err]   	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
00:08:37.821 [ERROR] [system.err]   	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
00:08:37.821 [ERROR] [system.err]   	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
00:08:37.821 [ERROR] [system.err]   	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
00:08:37.821 [ERROR] [system.err]   	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
00:08:37.821 [ERROR] [system.err]   	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
00:08:37.821 [ERROR] [system.err]   	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
00:08:37.821 [ERROR] [system.err]   	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
00:08:37.821 [ERROR] [system.err]   	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
00:08:37.821 [ERROR] [system.err]   	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
00:08:37.821 [ERROR] [system.err]   	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
00:08:37.821 [ERROR] [system.err]   	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
00:08:37.821 [ERROR] [system.err]   	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
00:08:37.821 [ERROR] [system.err]   	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
00:08:37.822 [ERROR] [system.err]   	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
00:08:37.822 [ERROR] [system.err]   	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
00:08:37.822 [ERROR] [system.err]   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
00:08:37.822 [ERROR] [system.err]   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
00:08:37.822 [ERROR] [system.err]   	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
00:08:37.822 [ERROR] [system.err]   	at java.lang.Thread.run(Thread.java:748)
00:08:37.823 [ERROR] [system.err] 1 error
00:08:37.823 [ERROR] [system.err] 4 warnings
```

Java source causing the error:
```java
public int indexOf(Object o) {
	if (o == null) {
		for (int i = 0; i < size; i++)
			if (elementData[i] == null)
				return i;
	} else {
		for (int i = 0; i < size; i++)
			if (o.equals(elementData[i]))
				return i;
	}
	return -1;
}
```

With braces after the for loops I can run errorprone successfully: 
```java
public int indexOf(Object o) {
	if (o == null) {
		for (int i = 0; i < size; i++) {
			if (elementData[i] == null) {
				return i;
			}	
		}	
	} else {
		for (int i = 0; i < size; i++) {
			if (o.equals(elementData[i])) {
				return i;
			}	
		}	
	}
	return -1;
}
```

**Comment by cushon** [comment] 2017-08-29 14:14
This is a duplicate of #711. It is fixed in version 2.1.1.

**Closed by cushon** 2017-08-29 14:14 UTC
