### ISSUE TITLE
NoClassDefFoundError or NoSuchMethodError in UnusedMethod jdk 17

### ISSUE THREAD

**Issue by uvilop** [google/error-prone#3054] opened 2022-03-17 07:51 UTC
Please report this at https://github.com/google/error-prone/issues/new and include the following:

     error-prone version: 2.11.0
     BugPattern: UnusedMethod
     Stack Trace:
     NoClassDefFoundError: com/sun/tools/javac/util/Filter
##      at java.base/ClassLoader.loadClass(ClassLoader.java:520)
        ... 18 more

     error-prone version: 2.11.0
     BugPattern: UnusedMethod
     Stack Trace:
##      at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)

javac openjdk or oracle
error_prone_core-2.11.0-with-dependencies.jar
dataflow-errorprone-3.15.0.jar

**Comment by rickie** [comment] 2022-03-17 08:18
This is a duplicate of https://github.com/google/error-prone/issues/2926. When a new version is released, updating should fix the issue.

**Closed** 2022-03-17 17:48 UTC
