### ISSUE TITLE
Exception from experimental bug pattern ArgumentParameterSwap

### ISSUE THREAD

**Issue by sebright** [google/error-prone#562] opened 2017-03-07 21:23 UTC
I got an exception from Error Prone when I built [`instrumentation-java`](https://github.com/google/instrumentation-java) with Bazel.  I built commit https://github.com/google/instrumentation-java/commit/87f8c78e5f887a220686b8b7d339dbcc7c38a1fa with the following command:

`bazel build :stats-core --javacopt='-Xep:ArgumentParameterSwap:ERROR'`.

```
ERROR: /home/travis/build/sebright/instrumentation-java/BUILD:29:1: Java compilation in rule '//:stats-core' failed: Worker process sent response with exit code: 1.
core/src/main/java/com/google/instrumentation/stats/RpcConstants.java:138: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
      DistributionViewDescriptor.create(
                                       ^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
     error-prone version: 2.0.15
     Stack Trace:
     java.lang.ClassCastException: com.sun.tools.javac.code.Type$ForAll cannot be cast to com.sun.tools.javac.code.Type$MethodType
  	at com.google.errorprone.bugpatterns.AbstractArgumentParameterChecker.isSubtypeHandleCompletionFailures(AbstractArgumentParameterChecker.java:217)
  	at com.google.errorprone.bugpatterns.AbstractArgumentParameterChecker.lambda$findReplacements$1(AbstractArgumentParameterChecker.java:191)
  	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
  	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
  	at java.util.Iterator.forEachRemaining(Iterator.java:116)
  	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
  	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
  	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
  	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
  	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:479)
  	at java.util.stream.ReferencePipeline.max(ReferencePipeline.java:515)
  	at com.google.errorprone.bugpatterns.AbstractArgumentParameterChecker.findReplacements(AbstractArgumentParameterChecker.java:198)
  	at com.google.errorprone.bugpatterns.AbstractArgumentParameterChecker.matchMethodInvocation(AbstractArgumentParameterChecker.java:145)
  	at com.google.errorprone.bugpatterns.ArgumentParameterSwap.matchMethodInvocation(ArgumentParameterSwap.java:42)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:952)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:144)
  	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1614)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:71)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:89)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at com.sun.source.util.TreeScanner.visitVariable(TreeScanner.java:223)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitVariable(ErrorProneScanner.java:1201)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitVariable(ErrorProneScanner.java:144)
  	at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:938)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:71)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:89)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:635)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:144)
  	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:778)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:71)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:89)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:650)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:144)
  	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:561)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:52)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:68)
  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:145)
  	at com.google.devtools.build.buildjar.javac.plugins.errorprone.ErrorPronePlugin.postFlow(ErrorPronePlugin.java:101)
  	at com.google.devtools.build.buildjar.javac.BlazeJavaCompiler.flow(BlazeJavaCompiler.java:112)
  	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1236)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:847)
  	at com.sun.tools.javac.api.JavacTaskImpl$1.call(JavacTaskImpl.java:97)
  	at com.sun.tools.javac.api.JavacTaskImpl$1.call(JavacTaskImpl.java:93)
  	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:128)
  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:93)
  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:87)
  	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:104)
  	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder$1.invokeJavac(SimpleJavaLibraryBuilder.java:163)
  	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:59)
  	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:166)
  	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:178)
  	at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:90)
  	at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:67)
  	at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:44)
```

Here is the full log: https://travis-ci.org/sebright/instrumentation-java/builds/208722254

**Comment by cushon** [comment] 2017-03-07 21:25
This is a duplicate of #490

**Closed by cushon** 2017-03-07 21:25 UTC
