### ISSUE TITLE
Error messages without pointing to the line of code in the file containing the error

### ISSUE THREAD

**Issue by zakharovsergey1000** [google/error-prone#2194] opened 2021-02-20 10:20 UTC
### Description of the problem / feature request:

There is a problem running the command "./gradlew runErrorProne" for the androidx library. It outputs some error messages without pointing to the line of code in the file containing the error.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

The steps to reproduce the issue revealed in my case:
1. setup androidx-main development environment as described here:
https://android.googlesource.com/platform/frameworks/support/
2. checkout this change:
https://android-review.googlesource.com/c/platform/frameworks/support/+/1592832
(patchset 1)
For example using this command:
repo download -b change-1592832 platform/frameworks/support 1592832
3. run command:
./gradlew runErrorProne

### What version of Error Prone are you using?

2.4.0

**Comment by cushon** [comment] 2021-02-20 15:19
Can you share the error message? Does using the latest release of Error Prone (currently 2.5.1) make a difference?

**Comment by zakharovsergey1000** [comment] 2021-02-21 07:21
The error messages looks like that:

Task :slice-builders:runErrorProne

error: [MissingSummary] A summary line is required on public/protected Javadocs.

    (see http://google.github.io/styleguide/javaguide.html#s7.2-summary-fragment)
error: [MissingSummary] A summary line is required on public/protected Javadocs.
    (see http://google.github.io/styleguide/javaguide.html#s7.2-summary-fragment)
error: [MissingSummary] A summary line is required on public/protected Javadocs.
    (see http://google.github.io/styleguide/javaguide.html#s7.2-summary-fragment)
error: [MissingSummary] A summary line is required on public/protected Javadocs.
    (see http://google.github.io/styleguide/javaguide.html#s7.2-summary-fragment)
error: [MissingSummary] A summary line is required on public/protected Javadocs.
    (see http://google.github.io/styleguide/javaguide.html#s7.2-summary-fragment)
error: [MissingSummary] A summary line is required on public/protected Javadocs.
    (see http://google.github.io/styleguide/javaguide.html#s7.2-summary-fragment)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
6 errors
Task :slice-builders:runErrorProne FAILED

Task :slice-core:runErrorProne

error: [MissingSummary] A summary line is required on public/protected Javadocs.

    (see http://google.github.io/styleguide/javaguide.html#s7.2-summary-fragment)
error: [MissingSummary] A summary line is required on public/protected Javadocs.
    (see http://google.github.io/styleguide/javaguide.html#s7.2-summary-fragment)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
Task :slice-core:runErrorProne FAILED

**Comment by cushon** [comment] 2021-02-21 07:31
> > Does using the latest release of Error Prone (currently 2.5.1) make a difference?
>
> `error: [MissingSummary] A summary line is required on public/protected Javadocs.`

This looks like a duplicate of https://github.com/google/error-prone/issues/1981, upgrading to 2.5.1 should fix it.

**Closed by cushon** 2021-02-21 07:31 UTC
