### ISSUE TITLE
NoSuchFieldError: error-prone fails due to break in for/do/switch statement

### ISSUE THREAD

**Issue by ChristianSchwarz** [google/error-prone#1576] opened 2020-04-16 20:15 UTC
I get the following error whenever error-prone hits a break-keyword in a do,for or switch statement.

I am running on OpenJDK 12.0.2
```
An unhandled exception was thrown by the Error Prone static analysis plugin.
error-prone version: 2.3.4
     BugPattern: Finally
     Stack Trace:
     java.lang.NoSuchFieldError: label
  	at com.google.errorprone.bugpatterns.Finally$FinallyJumpMatcher.<init>(Finally.java:171)
  	at com.google.errorprone.bugpatterns.Finally.matchBreak(Finally.java:79)
  	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:451)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBreak(ErrorProneScanner.java:528)
```

**Comment by ChristianSchwarz** [comment] 2020-04-16 20:47
I found the problem:

The class `com.sun.tools.javac.tree.JCBreak` doesn't have a field named `label` in OpenJDK12.0.2. 

Here is the problem:

```
public FinallyJumpMatcher(JCBreak jcBreak) {
      this.label = jcBreak.label;
                           ^^^^^ label is not declared 
```

**Comment by tbroyer** [comment] 2020-04-16 21:26
Duplicate of #1342, see also #1106. Fixed in https://github.com/google/error-prone/commit/a3bd193f0597d28aa382e911dfae8c9b57951ac0

**Closed** 2020-05-06 06:59 UTC
