### ISSUE TITLE
 BugPattern: TypeParameterUnusedInFormals

### ISSUE THREAD

**Issue by ChaosLee03** [google/error-prone#1441] opened 2019-12-06 03:30 UTC
### Description of the problem / feature request:

```
 error: An unhandled exception was thrown by the Error Prone static analysis plugin.
    [javac]   public <R, X extends Exception> R accept(CTypeVisitor<R, X> pVisitor) throws X {
 Please report this at https://github.com/google/error-prone/issues/new and include the following:
    [javac]      error-prone version: 2.3.3
    [javac]      BugPattern: TypeParameterUnusedInFormals
    [javac]      Stack Trace:
    [javac]      java.lang.NoSuchFieldError: bound
    [javac]   	at com.google.errorprone.bugpatterns.TypeParameterUnusedInFormals.matchMethod(TypeParameterUnusedInFormals.java:71)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:433)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:725)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:150)
    [javac]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:908)
    [javac]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:71)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
    [javac]   	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
    [javac]   	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
    [javac]   	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
    [javac]   	at jdk.compiler/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:188)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:535)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:150)
    [javac]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:818)
    [javac]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:71)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
    [javac]   	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
    [javac]   	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
    [javac]   	at jdk.compiler/com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:145)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:546)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:150)
    [javac]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:601)
    [javac]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:55)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
    [javac]   	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:151)
    [javac]   	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
    [javac]   	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1423)
    [javac]   	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1370)
    [javac]   	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:959)
    [javac]   	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:318)
    [javac]   	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
    [javac]   	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
    [javac]   	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
```

**Comment by tbroyer** [comment] 2019-12-06 07:22
JDK >11? ➡️ Duplicate of #1106

**Comment by tbroyer** [comment] 2019-12-06 07:23
Duplicate of #1352?

**Comment by ChaosLee03** [comment] 2019-12-06 08:57
> JDK >11? ➡️ Duplicate of #1106

yes, JDK 13.

**Comment by michaelhixson** [comment] 2019-12-06 18:02
I think this one is fixed in 2.3.4 by this commit: https://github.com/google/error-prone/commit/3c3c7979c260861e93154a52476df7bc0eb26127

**Comment by ChaosLee03** [comment] 2019-12-09 00:53
> I think this one is fixed in 2.3.4 by this commit: [3c3c797](https://github.com/google/error-prone/commit/3c3c7979c260861e93154a52476df7bc0eb26127)

Thx, but sorry, I'm still a beginner, I'm not good at it. How can I replace my 2.3.3 with it?

**Comment by tbroyer** [comment] 2019-12-09 06:26
How are you running ErrorProne? (an IDE? a build tool? which one?)

**Comment by ChaosLee03** [comment] 2019-12-10 00:29
> How are you running ErrorProne? (an IDE? a build tool? which one?)

I just followed the instructions from install.md to install the CPAChecker, but it failed.

**Comment by PhilippWendler** [comment] 2019-12-10 05:13
The latest CPAchecker version already uses error-prone 2.3.4, just upgrade. You either need to use Java 11 or disable error-prone while building CPAchecker (but that is off-topic here).

**Comment by cushon** [comment] 2020-05-20 20:54
#1352

**Closed by cushon** 2020-05-20 20:54 UTC
