### ISSUE TITLE
PackageLocation bug pattern throws exception on a windows platform 

### ISSUE THREAD

**Issue by VarSuren** [google/error-prone#439] opened 2016-07-18 17:29 UTC
error-prone version: 2.0.10
 
  java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/whoever/whatever/package-info.java
  	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
  	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
  	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
  	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
  	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
  	at java.nio.file.Paths.get(Paths.java:84)
  	at com.google.errorprone.bugpatterns.PackageLocation.getFilePath(PackageLocation.java:88)

Suggestion: check if it's a windows, remove first slash

**Comment by cushon** [comment] 2016-07-18 17:31
This is a duplicate of #432

**Closed by cushon** 2016-07-18 17:31 UTC
