### ISSUE TITLE
Not detecting new switch expressions

### ISSUE THREAD

**Issue by vivekkothari** [google/error-prone#2256] opened 2021-03-28 04:45 UTC
### Description of the problem / feature request:

I am using errorprone and it throws an exception if my code uses the new Java switch expressions.
My code is like

```
switch (name) {
      case "Event1" -> on(event1);
      case "Event2" -> on(event2);
      default -> logger.error("Invalid event " + name);
    }
```

```
 error: An unhandled exception was thrown by the Error Prone static analysis plugin.
    switch (name) {
    ^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
     error-prone version: 2.5.1
     BugPattern: FallThrough
     Stack Trace:
     java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because the return value of "com.sun.source.tree.CaseTree.getStatements()" is null
        at com.google.errorprone.bugpatterns.FallThrough.matchSwitch(FallThrough.java:60)
        at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:450)
        at com.google.errorprone.scanner.ErrorProneScanner.visitSwitch(ErrorProneScanner.java:824)
        at com.google.errorprone.scanner.ErrorProneScanner.visitSwitch(ErrorProneScanner.java:151)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCSwitch.accept(JCTree.java:1256)
        at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
        at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
        at jdk.compiler/com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:250)
        at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:521)
        at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:151)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1059)
        at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
        at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
        at jdk.compiler/com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:208)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:741)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:151)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:925)
        at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
        at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
        at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
        at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
        at jdk.compiler/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:189)
        at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:549)
```

### Feature requests: what underlying problem are you trying to solve with this feature?

N/A as it seem to be a bug.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Use a switch expression and compile code. 

### What version of Error Prone are you using?

id "net.ltgt.errorprone" version "2.0.0"

###  Have you found anything relevant by searching the web?

Didn't find anything concrete.

**Comment by jsannemo** [comment] 2021-04-16 16:53
Still present in error-prone 2.6.0

**Comment by vivekkothari** [comment] 2021-05-12 04:47
Yeah.. present in 2.6.0 too.

```
/path/to/class.java:47: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
    switch (request.getEntity()) {
    ^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
     error-prone version: 2.6.0
     BugPattern: SwitchDefault
     Stack Trace:
     java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because the return value of "com.sun.source.tree.CaseTree.getStatements()" is null
```

**Comment by cushon** [comment] 2021-05-29 19:19
The issue with `FallThrough` is a duplicate of #2118, https://github.com/google/error-prone/issues/2256#issuecomment-839430162 is a similar but distinct crash in `SwitchDefault`

**Closed** 2021-06-01 18:31 UTC
