### ISSUE TITLE
Error running error prone

### ISSUE THREAD

**Issue by marlukcz** [google/error-prone#3769] opened 2023-02-08 08:26 UTC
[ERROR]      Please report this at https://github.com/google/error-prone/issues/new and include the following:
[ERROR]   
[ERROR]      error-prone version: 2.17.0
[ERROR]      BugPattern: UnusedVariable
[ERROR]      Stack Trace:
[ERROR]      java.lang.IndexOutOfBoundsException: Range [702, 633) out of bounds for length 1106
[ERROR]   	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[ERROR]   	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:76)
[ERROR]   	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:313)
[ERROR]   	at java.base/java.util.Objects.checkFromToIndex(Objects.java:385)
[ERROR]   	at java.base/java.nio.HeapCharBuffer.subSequence(HeapCharBuffer.java:664)
[ERROR]   	at java.base/java.nio.HeapCharBuffer.subSequence(HeapCharBuffer.java:44)
[ERROR]   	at com.google.errorprone.VisitorState.getOffsetTokens(VisitorState.java:607)
[ERROR]   	at com.google.errorprone.fixes.SuggestedFixes.replaceIncludingComments(SuggestedFixes.java:1667)
[ERROR]   	at com.google.errorprone.bugpatterns.UnusedVariable.buildUnusedVarFixes(UnusedVariable.java:396)
[ERROR]   	at com.google.errorprone.bugpatterns.UnusedVariable.matchCompilationUnit(UnusedVariable.java:236)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:449)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:555)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:150)

my class looks like this: 
```
@Service
@RequiredArgsConstructor
@Slf4j
@FieldDefaults(level = AccessLevel.PRIVATE, makeFinal = true)
public class CachingCifsContextProvider {
    CifsContextProvider cifsContextProvider;

    private ConcurrentMap<EndpointsProperties.EndpointFolderProperties, CIFSContext> cache = new ConcurrentHashMap<>();

    public CIFSContext getCifsContext(EndpointsProperties.EndpointFolderProperties endpointFolder) {
        return cache.computeIfAbsent(endpointFolder, cifsContextProvider::getCifsContext);
    }

}
```

**Comment by rickie** [comment] 2023-02-17 13:56
This is probably a duplicate of #3594.

**Closed** 2023-03-01 20:01 UTC
