### ISSUE TITLE
Unhandled exception thrown on update from 2.20.0 to 2.21.0

### ISSUE THREAD

**Issue by ivanvandessel-wk** [google/error-prone#4036] opened 2023-08-02 15:47 UTC
*/*/*/*.java:1: error: An unhandled exception was thrown by the Error Prone static analysis plugin.

  Please report this at https://github.com/google/error-prone/issues/new and include the following:
2023-08-02T07:37:36.375367537Z   
2023-08-02T07:37:36.375371339Z      error-prone version: 2.21.0
2023-08-02T07:37:36.375375007Z      BugPattern: NotJavadoc
2023-08-02T07:37:36.375378473Z      Stack Trace:
error-prone version: 2.21.0
2023-08-02T07:37:36.375375007Z      BugPattern: NotJavadoc
2023-08-02T07:37:36.375378473Z      Stack Trace:
2023-08-02T07:37:36.375382503Z      java.lang.IllegalArgumentException: Overlapping ranges not permitted but found [252..257] overlapping [252..257]
2023-08-02T07:37:36.375386649Z         at com.google.common.base.Preconditions.checkArgument(Preconditions.java:445)
2023-08-02T07:37:36.375390900Z         at com.google.common.collect.ImmutableRangeSet$Builder.build(ImmutableRangeSet.java:807)
2023-08-02T07:37:36.375395064Z         at com.google.errorprone.bugpatterns.BugChecker.suppressedRegions(BugChecker.java:321)
2023-08-02T07:37:36.375398952Z         at com.google.errorprone.bugpatterns.javadoc.NotJavadoc.matchCompilationUnit(NotJavadoc.java:62)
2023-08-02T07:37:36.375415725Z         at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:449)
2023-08-02T07:37:36.375420109Z         at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:555)
2023-08-02T07:37:36.375424403Z         at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:150)
2023-08-02T07:37:36.375428505Z         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:614)
2023-08-02T07:37:36.375432625Z         at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:60)
2023-08-02T07:37:36.375436653Z         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:58)
2023-08-02T07:37:36.375440439Z         at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
2023-08-02T07:37:36.375444503Z         at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:156)
2023-08-02T07:37:36.375448606Z         at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
2023-08-02T07:37:36.375452539Z         at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1394)
2023-08-02T07:37:36.375458352Z         at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1341)
2023-08-02T07:37:36.375462598Z         at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:933)
2023-08-02T07:37:36.375466415Z         at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
2023-08-02T07:37:36.375470342Z         at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
2023-08-02T07:37:36.375474215Z         at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
2023-08-02T07:37:36.375478011Z         at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
2023-08-02T07:37:36.375497411Z         at org.gradle.internal.compiler.java.IncrementalCompileTask.call(IncrementalCompileTask.java:89)
2023-08-02T07:37:36.375501746Z         at org.gradle.api.internal.tasks.compile.AnnotationProcessingCompileTask.call(AnnotationProcessingCompileTask.java:94)
2023-08-02T07:37:36.375506062Z         at org.gradle.api.internal.tasks.compile.ResourceCleaningCompilationTask.call(ResourceCleaningCompilationTask.java:57)
2023-08-02T07:37:36.375510321Z         at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:56)
2023-08-02T07:37:36.375514400Z         at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:41)
2023-08-02T07:37:36.375518766Z         at org.gradle.api.internal.tasks.compile.daemon.AbstractIsolatedCompilerWorkerExecutor$CompilerWorkAction.execute(AbstractIsolatedCompilerWorkerExecutor.java:78)
2023-08-02T07:37:36.375523274Z         at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
2023-08-02T07:37:36.375527331Z         at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
2023-08-02T07:37:36.375531419Z         at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
2023-08-02T07:37:36.375535622Z         at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)
2023-08-02T07:37:36.375539491Z         at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:43)
2023-08-02T07:37:36.375543122Z         at org.gradle.workers.internal.FlatClassLoaderWorker.run(FlatClassLoaderWorker.java:32)
2023-08-02T07:37:36.375546942Z         at org.gradle.workers.internal.FlatClassLoaderWorker.run(FlatClassLoaderWorker.java:22)
2023-08-02T07:37:36.375831291Z         at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:87)
2023-08-02T07:37:36.375844233Z         at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:56)
2023-08-02T07:37:36.375848803Z         at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:138)
2023-08-02T07:37:36.375853140Z         at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
2023-08-02T07:37:36.375857504Z         at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:135)
2023-08-02T07:37:36.375861688Z         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-08-02T07:37:36.375865844Z         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-08-02T07:37:36.375869997Z         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-08-02T07:37:36.375873547Z         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-08-02T07:37:36.375877191Z         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
2023-08-02T07:37:36.375885557Z         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
2023-08-02T07:37:36.375890146Z         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
2023-08-02T07:37:36.375894553Z         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
2023-08-02T07:37:36.375899400Z         at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
2023-08-02T07:37:36.375903525Z         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
2023-08-02T07:37:36.375907421Z         at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
2023-08-02T07:37:36.375911273Z         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-08-02T07:37:36.375915187Z         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-08-02T07:37:36.375919077Z         at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Stephan202** [comment] 2023-08-02 16:01
This looks like a duplicate of #4034.

**Closed** 2023-08-02 17:49 UTC
