### ISSUE TITLE
[Maven] "Too many open files" during compilation (mvn clean package)

### ISSUE THREAD

**Issue by monku** [google/error-prone#737] opened 2017-09-04 11:00 UTC
Hi.

I was trying to introduce error-prone to our project (almost 17000 source files).
Running it on my local machine (windows) went fine.

But when I tried to run build on our teamcity server (linux agents) I'm getting "Too many open files".
Even when we raised the file limit to "500 000" the run just survived for a bit longer.

Without error prone it works fine even with a lot lower limit.

My maven compiler configuration:
`      
<plugin>

        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.2</version>
        <configuration>
          <compilerId>javac-with-errorprone</compilerId>
          <forceJavacCompilerUse>true</forceJavacCompilerUse>
          <encoding>ISO-8859-1</encoding>
          <source>1.8</source>
          <target>1.8</target>
          <fork>true</fork>
          <maxmem>256m</maxmem>
        </configuration>
          <dependencies>
            <dependency>
              <groupId>org.codehaus.plexus</groupId>
              <artifactId>plexus-compiler-javac-errorprone</artifactId>
              <version>2.8.2</version>
            </dependency>
              <dependency>
              <groupId>com.google.errorprone</groupId>
              <artifactId>error_prone_core</artifactId>
              <version>2.1.1</version>
            </dependency>
          </dependencies>
      </plugin>`

**Comment by monku** [comment] 2017-09-06 08:30
Hi.

I've found the configuration working for me:
`

<dependencies>

            <dependency>
              <groupId>org.codehaus.plexus</groupId>
              <artifactId>plexus-compiler-javac-errorprone</artifactId>
              <version>**2.8**</version>
            </dependency>
              
              <dependency>
              <groupId>com.google.errorprone</groupId>
              <artifactId>error_prone_core</artifactId>
              <version>**2.0.10**</version>
            </dependency>
</dependencies>`

With those versions compilation does not cause "too many open files" errors and passes nicely. But that prevents me from updating to more recent version of a plugin, so still please help.

**Comment by monku** [comment] 2017-09-06 08:32
Oh.. and Also I tried version of "error_prone_core" 2.0.5, 2.0.13, 2.0.19 of which none worked

**Comment by monku** [comment] 2017-09-06 16:52
Today I was albe to pinpointed  the bug to this commit: 567a2f4e3fc9fa0fceb9afbac2ccc938d9be4419

Upgrade from:1.9.0-dev-r2973-2 to 9-dev-r3297-1

Causes the issue on my side (Too many open files during compilation)

**Comment by eaftan** [comment] 2017-09-06 17:37
Thank you for the detective work!  This may be a problem in upstream javac 9; the commit you pinpointed the bug to updates the version of javac we are using to a newer revision of javac 9.

Could you try installing an [Early Access build of Java 9](http://jdk.java.net/9/) and using that to compile your project, without Error Prone?

**Comment by monku** [comment] 2017-09-06 18:29
@eaftan : That might be a challange. Because our project is not really ready for java 
Also the problem does not occur on my dev machine (Windows) but only on our teamcity agent machines (linux and I don't have a way to install anything there). I will try.

In the mean time Id' like to try something else: 
- adding most recent java 9 classes to error-prone 

Can you suggest how can I try this? (is there a list of jars/class files that I might include as a dependency instead of "com.google.errorprone:javac" or maybe you could provide me with most recent version of this artifact?

**Comment by eaftan** [comment] 2017-09-08 18:21
Let's try applying http://file-leak-detector.kohsuke.org/ to Error Prone and see if we are leaking file handles.

**Comment by nglorioso** [comment] 2017-09-08 19:08
@monku Thanks for your detective work.

You can configure the maven-compiler-plugin to use a different javac executable (instead of replacing it with the specific compiler-id): https://maven.apache.org/plugins/maven-compiler-plugin/examples/compile-using-different-jdk.html

I think you can get the EA build of javac9 and move your maven build to point at that executable and get the behavior you're looking for within maven.

To be clear: is this a single bulk compile of ~17,000 source files, or a number of compiles of modules that total ~17,000 sources? Is the source available for reproducing? I'll see what I can do with the leak detector in the meantime on the source available to us.

**Comment by monku** [comment] 2017-09-08 19:51
@eaftan I tried that on my windows machine and got no leakage during build with error-prone (but on my local this does not happen)

One thing that just came to my mind is that our teamcity uses different JDK (1.8u73 or something around that, and my local is 1.8u131), I need to investigate if change of that will help.

@nglorioso I tried running maven with javac9 compiler and failed the compilation on some maven error 
 and currently I cannot spend much more time on this. I will try to get back to this next week.

There are multiple modules, the biggest one is around 3000 source files, but as far as I remember we are not getting there yet when the error is happening. The software is a closed source project that I work during my day job and I cannot share it. If I could I would share it in my first entry here :-)

**Comment by nglorioso** [comment] 2017-09-08 22:24
@monku I understand, no worries. 

I was unable to reproduce the too many file described with a local ant-style build with our JDK and ~50,000 dummy empty classes (ulimit of 32k). I haven't tried setting this up with Maven.

https://confluence.jetbrains.com/display/TCD10/Reporting+Issues#ReportingIssues-"Toomanyopenfiles"Error might have more about reporting something specific to TeamCity

**Comment by monku** [comment] 2017-09-12 10:51
@nglorioso , @eaftan : I just checked and it looks like maven/teamcity is not closing connections to dependencies. Formal build:
13 /opt/.m2/com/google/guava/guava/16.0.1/guava-16.0.1.jar
Faulty build:
440 /opt/.m2/com/google/guava/guava/16.0.1/guava-16.0.1.jar

I just checked the build on our jenkins server and it was success. So I guess there is a problem with teamcity agent here.

Thanks for your time investigating that! I will try reporting an issue to Teamcity.

**Comment by eaftan** [comment] 2017-09-12 17:08
Thanks for the update.  Closing this issue.

**Closed by eaftan** 2017-09-12 17:08 UTC
