### ISSUE TITLE
Uncaught IndexOutOfBoundsException from DoNotMock rule

### ISSUE THREAD

**Issue by kennymacleod** [google/error-prone#3620] opened 2022-12-21 10:49 UTC
I'm getting an uncaught exception from ErrorProne 2.16 on Java 11 when compiling my code. The stack trace is below.

I'm not 100% sure what it's having an issue with, but I suspect it's this method:

`
@Bean
VelocityManager velocityManager() {
    return Mockito.mock();
}
`

```
21-Dec-2022 10:35:17 | [main] [ERROR]      error-prone version: 2.16
-- | --
21-Dec-2022 10:35:17 | [main] [ERROR]      BugPattern: DoNotMock
21-Dec-2022 10:35:17 | [main] [ERROR]      Stack Trace:
21-Dec-2022 10:35:17 | [main] [ERROR]      java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.tools.javac.util.List.get(List.java:490)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.bugpatterns.AbstractMockChecker.lambda$extractFirstArg$2(AbstractMockChecker.java:172)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.bugpatterns.AbstractMockChecker$TypeExtractor.lambda$or$1(AbstractMockChecker.java:145)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.bugpatterns.AbstractMockChecker.matchMethodInvocation(AbstractMockChecker.java:236)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:449)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:746)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:150)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1666)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.source.util.TreeScanner.visitReturn(TreeScanner.java:469)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.scanner.ErrorProneScanner.visitReturn(ErrorProneScanner.java:817)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.scanner.ErrorProneScanner.visitReturn(ErrorProneScanner.java:150)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1570)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:520)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:150)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1048)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:206)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:740)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:150)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:898)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:548)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:150)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:560)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:150)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.scanner.Scanner.scan(Scanner.java:58)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
21-Dec-2022 10:35:17 | [main] [ERROR]           at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1414)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1361)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:960)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
21-Dec-2022 10:35:17 | [main] [ERROR]           at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
21-Dec-2022 10:35:17 | [main] [ERROR]           at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
21-Dec-2022 10:35:17 | [main] [ERROR]           at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
21-Dec-2022 10:35:17 | [main] [ERROR]           at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1134)
21-Dec-2022 10:35:17 | [main] [ERROR]           at org.apache.maven.plugin.compiler.TestCompilerMojo.execute(TestCompilerMojo.java:180)
21-Dec-2022 10:35:17 | [main] [ERROR]           at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
21-Dec-2022 10:35:17 | [main] [ERROR]           at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
21-Dec-2022 10:35:17 | [main] [ERROR]           at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
21-Dec-2022 10:35:17 | [main] [ERROR]           at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
21-Dec-2022 10:35:17 | [main] [ERROR]           at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
21-Dec-2022 10:35:17 | [main] [ERROR]           at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
21-Dec-2022 10:35:17 | [main] [ERROR]           at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
21-Dec-2022 10:35:17 | [main] [ERROR]           at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:210)
21-Dec-2022 10:35:17 | [main] [ERROR]           at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:195)
21-Dec-2022 10:35:17 | [main] [ERROR]           at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
21-Dec-2022 10:35:17 | [main] [ERROR]           at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
21-Dec-2022 10:35:17 | [main] [ERROR]           at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
21-Dec-2022 10:35:17 | [main] [ERROR]           at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
21-Dec-2022 10:35:17 | [main] [ERROR]           at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
21-Dec-2022 10:35:17 | [main] [ERROR]           at java.base/java.lang.Thread.run(Thread.java:829)
21-Dec-2022 10:35:17


```

**Comment by tbroyer** [comment] 2022-12-21 11:00
Duplicate of #3609

**Comment by graememorgan** [comment] 2022-12-23 11:07
The issue was the new argumentless `mock()` method.

**Closed by graememorgan** 2022-12-23 11:07 UTC
