### ISSUE TITLE
An unhandled exception was thrown by the Error Prone static analysis plugin

### ISSUE THREAD

**Issue by brwoods** [google/error-prone#1300] opened 2019-06-21 18:17 UTC
### Description of the problem / feature request:

Error:Error:line (15)java: An unhandled exception was thrown by the Error Prone static analysis plugin.
error-prone version: 2.3.3
     BugPattern: Finally
     Stack Trace:
     java.lang.NoSuchFieldError: label

### Feature requests: what underlying problem are you trying to solve with this feature?

N/A

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Install plugin into IntelliJ and use the plugin.

### What version of Error Prone are you using?

error-prone version: 2.3.3

###  Have you found anything relevant by searching the web?

Error message instructs me to report issue here.

[error_prone_report.txt](https://github.com/google/error-prone/files/3315621/error_prone_report.txt)
[error_prone_report.txt](https://github.com/google/error-prone/files/3315622/error_prone_report.txt)

**Comment by sumitbhagwani** [comment] 2019-07-09 19:42
Duplicate of #1301 -- which is probably duplicate of #1106 ?

**Closed** 2021-01-07 20:51 UTC
