### ISSUE TITLE
Not able to run Butler App through IntellIJ IDE

### ISSUE THREAD

**Issue by priyanka-oruganti** [google/error-prone#2226] opened 2021-03-08 09:55 UTC
> ATTENTION! Please read and follow:
> - if this is a _question_ about Error Prone, send it to error-prone-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

> Not able to run Butler App through Intellij IDE , throwing error

### Feature requests: what underlying problem are you trying to solve with this feature?

> Need to setup the backend in local environment

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Try to run the butler app in intellij IDE using run configurations

### What version of Error Prone are you using?

> 2.4.0

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>Not really
<img width="1436" alt="Screenshot 2021-03-08 at 3 24 42 PM" src="https://user-images.githubusercontent.com/79128927/110305172-72e84480-8022-11eb-84bd-e1594652dc18.png">

> Places to look:
> - GitHub issues: https://github.com/google/error-prone/issues
> - email threads on https://groups.google.com/forum/#!forum/error-prone-discuss

**Comment by cushon** [comment] 2021-03-08 18:36
* Does this still happen if you upgrade to Error Prone 2.5.1?
* Can you share the full stack trace by copy-pasting the text, instead of a screenshot? 
* Can you share an example that reproduces the crash?

**Comment by priyanka-oruganti** [comment] 2021-03-09 04:53
Hi,
 
I tried earlier also, I didn't get error prone comilier 2.5.1. Can you please help me out.
 
Thanks,
Priyanka.
----- Original message -----From: Liam Miller-Cushon <notifications@github.com>To: google/error-prone <error-prone@noreply.github.com>Cc: Priyanka Oruganti <devi.oruganti@ibm.com>, Author <author@noreply.github.com>Subject: [EXTERNAL] Re: [google/error-prone] Not able to run Butler App through IntellIJ IDE (#2226)Date: Tue, Mar 9, 2021 12:07 AM  
 
        Does this still happen if you upgrade to Error Prone 2.5.1?        Can you share the full stack trace by copy-pasting the text, instead of a screenshot?        Can you share an example that reproduces the crash?

**Comment by cushon** [comment] 2021-03-13 23:19
This is a duplicate of https://github.com/google/error-prone/issues/1991

The fix is to update to the latest versions of the [IntelliJ plugin](https://plugins.jetbrains.com/plugin/7349-error-prone-compiler) and Error Prone.

**Closed by cushon** 2021-03-13 23:19 UTC
