### ISSUE TITLE
AlreadyChecked: unhandled exception

### ISSUE THREAD

**Issue by Xander-Polishchuk** [google/error-prone#4600] opened 2024-10-02 04:46 UTC
> error: An unhandled exception was thrown by the Error Prone static analysis plugin.
> package [redacted];
> ^
>     Please report this at https://github.com/google/error-prone/issues/new and include the following:

<details>
  <summary>Stack trace:</summary>

```java  
     error-prone version: 2.33.0
     BugPattern: AlreadyChecked
     Stack Trace:
     java.lang.AssertionError: isSameType UNKNOWN
  	at jdk.compiler/com.sun.tools.javac.code.Types$5.visitType(Types.java:1379)
  	at jdk.compiler/com.sun.tools.javac.code.Types$5.visitType(Types.java:1351)
  	at jdk.compiler/com.sun.tools.javac.code.Type.accept(Type.java:223)
  	at jdk.compiler/com.sun.tools.javac.code.Types$DefaultTypeVisitor.visit(Types.java:4900)
  	at jdk.compiler/com.sun.tools.javac.code.Types.isSameType(Types.java:1343)
  	at com.google.errorprone.util.ASTHelpers.isSameType(ASTHelpers.java:1343)
  	at com.google.errorprone.bugpatterns.AlreadyChecked$IfScanner.scan(AlreadyChecked.java:210)
  	at com.google.errorprone.bugpatterns.AlreadyChecked$IfScanner.scan(AlreadyChecked.java:76)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitVariable(TreeScanner.java:241)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:1040)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
  	at com.google.errorprone.bugpatterns.BugChecker$SuppressibleTreePathScanner.scan(BugChecker.java:591)
  	at com.google.errorprone.bugpatterns.AlreadyChecked$IfScanner.scan(AlreadyChecked.java:211)
  	at com.google.errorprone.bugpatterns.AlreadyChecked$IfScanner.scan(AlreadyChecked.java:76)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitBindingPattern(TreeScanner.java:807)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBindingPattern.accept(JCTree.java:2321)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
  	at com.google.errorprone.bugpatterns.BugChecker$SuppressibleTreePathScanner.scan(BugChecker.java:591)
  	at com.google.errorprone.bugpatterns.AlreadyChecked$IfScanner.scan(AlreadyChecked.java:211)
  	at com.google.errorprone.bugpatterns.AlreadyChecked$IfScanner.scan(AlreadyChecked.java:76)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:119)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitDeconstructionPattern(TreeScanner.java:868)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCRecordPattern.accept(JCTree.java:2474)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
  	at com.google.errorprone.bugpatterns.BugChecker$SuppressibleTreePathScanner.scan(BugChecker.java:591)
  	at com.google.errorprone.bugpatterns.AlreadyChecked$IfScanner.scan(AlreadyChecked.java:211)
  	at com.google.errorprone.bugpatterns.AlreadyChecked$IfScanner.scan(AlreadyChecked.java:76)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitPatternCaseLabel(TreeScanner.java:852)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCPatternCaseLabel.accept(JCTree.java:2424)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
  	at com.google.errorprone.bugpatterns.BugChecker$SuppressibleTreePathScanner.scan(BugChecker.java:591)
  	at com.google.errorprone.bugpatterns.AlreadyChecked$IfScanner.scan(AlreadyChecked.java:211)
  	at com.google.errorprone.bugpatterns.AlreadyChecked$IfScanner.scan(AlreadyChecked.java:76)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitCase(TreeScanner.java:399)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCase.accept(JCTree.java:1374)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
  	at com.google.errorprone.bugpatterns.BugChecker$SuppressibleTreePathScanner.scan(BugChecker.java:591)
  	at com.google.errorprone.bugpatterns.AlreadyChecked$IfScanner.scan(AlreadyChecked.java:211)
  	at com.google.errorprone.bugpatterns.AlreadyChecked$IfScanner.scan(AlreadyChecked.java:76)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:119)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitSwitch(TreeScanner.java:368)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCSwitch.accept(JCTree.java:1309)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
  	at com.google.errorprone.bugpatterns.BugChecker$SuppressibleTreePathScanner.scan(BugChecker.java:591)
  	at com.google.errorprone.bugpatterns.AlreadyChecked$IfScanner.scan(AlreadyChecked.java:211)
  	at com.google.errorprone.bugpatterns.AlreadyChecked$IfScanner.scan(AlreadyChecked.java:76)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:272)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1104)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
  	at com.google.errorprone.bugpatterns.BugChecker$SuppressibleTreePathScanner.scan(BugChecker.java:591)
  	at com.google.errorprone.bugpatterns.AlreadyChecked$IfScanner.scan(AlreadyChecked.java:201)
  	at com.google.errorprone.bugpatterns.AlreadyChecked$IfScanner.scan(AlreadyChecked.java:76)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:224)
  	at com.google.errorprone.bugpatterns.AlreadyChecked$IfScanner.lambda$visitMethod$0(AlreadyChecked.java:159)
  	at com.google.errorprone.bugpatterns.AlreadyChecked$IfScanner.withinMethod(AlreadyChecked.java:168)
  	at com.google.errorprone.bugpatterns.AlreadyChecked$IfScanner.visitMethod(AlreadyChecked.java:159)
  	at com.google.errorprone.bugpatterns.AlreadyChecked$IfScanner.visitMethod(AlreadyChecked.java:76)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:948)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
  	at com.google.errorprone.bugpatterns.BugChecker$SuppressibleTreePathScanner.scan(BugChecker.java:591)
  	at com.google.errorprone.bugpatterns.AlreadyChecked$IfScanner.scan(AlreadyChecked.java:201)
  	at com.google.errorprone.bugpatterns.AlreadyChecked$IfScanner.scan(AlreadyChecked.java:76)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:119)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:203)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:855)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
  	at com.google.errorprone.bugpatterns.BugChecker$SuppressibleTreePathScanner.scan(BugChecker.java:591)
  	at com.google.errorprone.bugpatterns.AlreadyChecked$IfScanner.scan(AlreadyChecked.java:201)
  	at com.google.errorprone.bugpatterns.AlreadyChecked$IfScanner.scan(AlreadyChecked.java:76)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:119)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:203)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:855)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
  	at com.google.errorprone.bugpatterns.BugChecker$SuppressibleTreePathScanner.scan(BugChecker.java:591)
  	at com.google.errorprone.bugpatterns.AlreadyChecked$IfScanner.scan(AlreadyChecked.java:201)
  	at com.google.errorprone.bugpatterns.AlreadyChecked$IfScanner.scan(AlreadyChecked.java:76)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:119)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:152)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:623)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:66)
  	at com.google.errorprone.bugpatterns.BugChecker$SuppressibleTreePathScanner.scan(BugChecker.java:596)
  	at com.google.errorprone.bugpatterns.AlreadyChecked.matchCompilationUnit(AlreadyChecked.java:70)
  	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:449)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:555)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:150)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:623)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:66)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:58)
  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:227)
  	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:133)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1436)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1383)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:963)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
  	at org.gradle.internal.compiler.java.IncrementalCompileTask.call(IncrementalCompileTask.java:92)
  	at org.gradle.api.internal.tasks.compile.AnnotationProcessingCompileTask.call(AnnotationProcessingCompileTask.java:94)
  	at org.gradle.api.internal.tasks.compile.ResourceCleaningCompilationTask.call(ResourceCleaningCompilationTask.java:57)
  	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:59)
  	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:41)
  	at org.gradle.api.internal.tasks.compile.daemon.AbstractIsolatedCompilerWorkerExecutor$CompilerWorkAction.execute(AbstractIsolatedCompilerWorkerExecutor.java:78)
  	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
  	at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:54)
  	at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:48)
  	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)
  	at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:48)
  	at org.gradle.workers.internal.FlatClassLoaderWorker.run(FlatClassLoaderWorker.java:32)
  	at org.gradle.workers.internal.FlatClassLoaderWorker.run(FlatClassLoaderWorker.java:22)
  	at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:102)
  	at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:71)
  	at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:146)
  	at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
  	at org.gradle.process.internal.worker.request.WorkerAction.lambda$run$0(WorkerAction.java:143)
  	at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
  	at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:135)
  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
  	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
  	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
  	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
  	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
  	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
  	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
  	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  	at java.base/java.lang.Thread.run(Thread.java:1583)
```

</details>

JDK: 
```
openjdk 21.0.2 2024-01-16
OpenJDK Runtime Environment GraalVM CE 21.0.2+13.1 (build 21.0.2+13-jvmci-23.1-b30) 
```

I was able to reproduce with following sample:
```
private static class Sample {

    void unhandledException(boolean condition) {
        if (condition) {
            return;
        }

        switch (new Foo("value")) {
            case Foo(final var value) -> System.out.println(value);
        }
    }

    record Foo(String value) {}
}
```
It requires both arbitrary condition and arbitrary record pattern in the same method

**Comment by cushon** [comment] 2024-10-04 22:12
I can reproduce with JDK 22, but not JDK 23. Bisecting shows it was fixed in JDK 23+26, I think by this change: https://bugs.openjdk.org/browse/JDK-8332725

Since this is a javac bug there isn't a good workaround in Error Prone, the best solution may be to update to JDK 23 or newer.

**Closed** 2024-10-10 16:58 UTC
