### ISSUE TITLE
Memoized state creates flaky build issues

### ISSUE THREAD

**Issue by kageiit** [google/error-prone#588] opened 2017-03-25 20:45 UTC
In `ErrorProneAnalyzer`, there is memoized state - https://github.com/google/error-prone/blob/de639a1ef4d962b984741ed346f0519c85eb6122/check_api/src/main/java/com/google/errorprone/ErrorProneAnalyzer.java#L67

This causes issues when custom checkers classes loaded onto the classpath via the jars on the processrpath are no longer present/renamed etc.

Ideally, the compiler should be stateless so that when invoked in memory/compiler daemons in build systems like buck/gradle/bazel, further invocations are also always idempotent.

Stacktrace:
```
BUILD FAILED: //tooling/error-prone/test-code-checkers:src_main failed with exit code 1:
javac_jar
stderr: An exception has occurred in the compiler (9-internal). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.util.ServiceConfigurationError: com.google.errorprone.bugpatterns.BugChecker: Provider com.example.CustomChecker not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
	at java.util.ServiceLoader$LazyIterator.access$700(ServiceLoader.java:323)
	at java.util.ServiceLoader$LazyIterator$2.run(ServiceLoader.java:407)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:409)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.errorprone.scanner.ScannerSupplier.fromBugCheckerClasses(ScannerSupplier.java:73)
	at com.google.errorprone.ErrorPronePlugins.loadPlugins(ErrorPronePlugins.java:53)
	at com.google.errorprone.ErrorProneAnalyzer.lambda$scansPlugins$0(ErrorProneAnalyzer.java:73)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:160)
	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:145)
	at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1277)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1226)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:840)
	at com.sun.tools.javac.api.JavacTaskImpl$1.call(JavacTaskImpl.java:97)
	at com.sun.tools.javac.api.JavacTaskImpl$1.call(JavacTaskImpl.java:93)
	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:128)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:93)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:87)
	at com.google.errorprone.BaseErrorProneJavaCompiler$1.call(BaseErrorProneJavaCompiler.java:99)
	at com.facebook.buck.jvm.java.Jsr199Javac.buildWithClasspath(Jsr199Javac.java:292)
	at com.facebook.buck.jvm.java.Jsr199Javac.buildWithClasspath(Jsr199Javac.java:155)
	at com.facebook.buck.jvm.java.JavacStep.performBuild(JavacStep.java:200)
	at com.facebook.buck.jvm.java.JavacStep.tryBuildWithFirstOrderDeps(JavacStep.java:190)
	at com.facebook.buck.jvm.java.JavacStep.execute(JavacStep.java:151)
	at com.facebook.buck.jvm.java.JavacDirectToJarStep.execute(JavacDirectToJarStep.java:95)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:47)
	at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:1466)
	at com.facebook.buck.rules.CachingBuildEngine.lambda$15(CachingBuildEngine.java:339)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:81)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

cc @msridhar

**Comment by kageiit** [comment] 2017-03-25 20:46
After killing the compiler daemon jvm, the next compilation command worked without failures as intended

**Comment by msridhar** [comment] 2017-04-01 00:11
We dug a bit more into this issue today, and realized the description above is not quite correct; memoization does not seem to be the problem.  Here is what is going on.  We are using Error Prone with Buck and the Buck daemon, with java compilation run in-process.  We do one build successfully.  Then, we make a change that deletes a plug-in checker.  Now, when we try to do another build (with the same daemon process), we get a crash with the stack above, indicating that the deleted checker cannot be loaded.  Digging into to the code, this means that somehow, the `ServiceLoader` is seeing a stale version of the `META-INF/services/com.google.errorprone.bugpatterns.BugChecker` file, which still includes the name of the deleted checker.  But, it does see the up-to-date jar when doing the actual class loading, and hence cannot load the missing class and crashes.  When we disable the Buck daemon, we cannot reproduce the issue, which means it is likely due to some global state somewhere.

At this point, we are stumped as to where the bug might be, since we cannot track down the stale state.  (It could even be a JDK bug, who knows.)  Just wanted to write this down in case it helps someone recognize the problem.

**Comment by cushon** [comment] 2021-01-08 19:26
Closing since since there isn't a good way to reproduce this and it's not clear if it's a bug in the JDK, or the daemon, or Error Prone itself. Feel free to re-open if you reencounter this.

**Closed by cushon** 2021-01-08 19:26 UTC
Labels: not-reproducible
