### ISSUE TITLE
An unhandled exception was thrown by the Error Prone static analysis plugin

### ISSUE THREAD

**Issue by originalrusyn** [google/error-prone#438] opened 2016-07-18 08:51 UTC
`error-prone version: 2.0.10
     Stack Trace:
     java.nio.file.InvalidPathException: Illegal char <:> at index 2: /D:/git_repo/server/track-repo/src/main/java/mobi/nowtechnologies/server/trackrepo/auto/encode/service/TrackEncodeStatusService.java
  	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
  	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
  	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
  	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
  	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
  	at java.nio.file.Paths.get(Paths.java:84)
  	at com.google.errorprone.bugpatterns.PackageLocation.getFilePath(PackageLocation.java:88)
  	at com.google.errorprone.bugpatterns.PackageLocation.matchCompilationUnit(PackageLocation.java:69)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:646)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:146)
  	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:561)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:53)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:70)
  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:45)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:125)
  	at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:113)
  	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1303)
  	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1247)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:858)
  	at com.sun.tools.javac.main.Main.compile(Main.java:253)
  	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:190)
  	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:101)
  	at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:131)
  	at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:73)
  	at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne$CompilerInvoker.compile(JavacCompilerWithErrorProne.java:219)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:483)
  	at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne.performCompile(JavacCompilerWithErrorProne.java:91)
  	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:825)
  	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
  	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
  	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
  	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:483)
  	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
  	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
  	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
  	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
  	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:483)
  	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
1 error`

**Comment by Stephan202** [comment] 2016-07-18 08:55
Looks like a duplicate of #432.

**Comment by originalrusyn** [comment] 2016-07-18 09:47
yes

**Comment by eaftan** [comment] 2016-07-18 17:03
Closing as a dupe of #432.

**Closed by eaftan** 2016-07-18 17:03 UTC
